### ISSUE TITLE
No Output Files from Docker on Windows

### ISSUE THREAD

**Issue by jmhatch** [kahst/BirdNET#14]
Hi, 

I'm new to using BirdNET via Docker Desktop. I followed the instructions on how to build and run BirdNET using Docker on my Windows machine. Everything seems to work correctly, except no output files are produced?

As a test, I ran BirdNET on the example audio files provided as part of the BirdNET GitHub repo. I ran the following,

```
>docker run -v ./BirdNET/example:/audio birdnet --i audio 

FILES IN DATASET: 2
LOADING SNAPSHOT BirdNET_Soundscape_Model.pkl ... DONE!
BUILDING BirdNET MODEL... DONE!
IMPORTING MODEL PARAMS... DONE!
COMPILING THEANO TEST FUNCTION FUNCTION... DONE!
LOADING eBIRD GRID DATA...
```
When I go to look in the directory `./BirdNET/example` I see the audio files, but no output files? Any suggestions? I was expecting 2 output files named Soundscape_1.BirdNET.selections.txt and Soundscape_2.BirdNET.selections.txt. No errors are thrown, so I'm not sure if it's getting hung up somewhere or the files are not being written to my local machine and are getting lost in the VM.

Thanks!

**Comment by lenawarbler** [comment]
Hey jmhatch! I just set up birdNET on Windows and also had this issue.. Then I realized I did not need Docker, and was able to run everything with Ubuntu. Do you absolutely need Docker?

**Comment by jmhatch** [comment]
Hi @lenawarbler! Yeah, unless there is a way to run Ubuntu on a windows machine without using Docker? I don’t have access to an Ubuntu instance unless I setup something in the cloud. Any ideas? I’m kind of stuck with Windows.

**Comment by lenawarbler** [comment]
Hmm my impression is that WSL / Ubuntu for windows (2020?) came out after birdNET was published (2019?), so Docker is not needed anymore. I was able to install this setup on my Windows 10 computer and run birdNET without Docker: https://ubuntu.com/wsl

**Comment by jmhatch** [comment]
@lenawarbler I must be living under a rock 🤣! I'll install that on my personal laptop and go from there. Thanks for the help!
